{
  "formatVersion": "1.1",
  "component": {
    "group": "th.tamkungz",
    "module": "letyourfriendeating-fabric-1.20.1",
    "version": "1.0.4-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.136"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "letyourfriendeating-fabric-1.20.1-1.0.4-2.jar",
          "url": "letyourfriendeating-fabric-1.20.1-1.0.4-2.jar",
          "size": 130058,
          "sha512": "2767894f23a0407767da78a81d87e3d58cd7370557bd7d26980e9a4cac5e318fb897baa08a8ecc2f9b6fb6a0fa348391e46c86fee135d3f1e040c07e02193b54",
          "sha256": "813f16d3620adcab27776b43930c9d32e5383ba2b0f7ddaa8abc7feb96890bfe",
          "sha1": "b163d159b56590fc2ad225a5f38fd09107aa23eb",
          "md5": "44e617dc8ebd826d08e5d2de08835907"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.136"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "letyourfriendeating-fabric-1.20.1-1.0.4-2.jar",
          "url": "letyourfriendeating-fabric-1.20.1-1.0.4-2.jar",
          "size": 130058,
          "sha512": "2767894f23a0407767da78a81d87e3d58cd7370557bd7d26980e9a4cac5e318fb897baa08a8ecc2f9b6fb6a0fa348391e46c86fee135d3f1e040c07e02193b54",
          "sha256": "813f16d3620adcab27776b43930c9d32e5383ba2b0f7ddaa8abc7feb96890bfe",
          "sha1": "b163d159b56590fc2ad225a5f38fd09107aa23eb",
          "md5": "44e617dc8ebd826d08e5d2de08835907"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "letyourfriendeating-fabric-1.20.1-1.0.4-2-sources.jar",
          "url": "letyourfriendeating-fabric-1.20.1-1.0.4-2-sources.jar",
          "size": 116912,
          "sha512": "dc90413a9f494c1661f70a47ed43c67730f938a1e21412559e71ee5db9b24ca9429b55a5facf272a820f964877005c541ed2e6f2000d82e4d9d819d1bba32247",
          "sha256": "ad2ed1e7a839ac17303a3c514442341c650c68a829ccadc275312a7e1a5c35dc",
          "sha1": "12a851d2a89e10f943310367730d88870695becf",
          "md5": "ad3cec078cf9f0bf9c0d5fa1ecb222af"
        }
      ]
    }
  ]
}
