{
  "formatVersion": "1.1",
  "component": {
    "group": "th.in.tamkungz",
    "module": "magicsrebirthlib-forge",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magicsrebirthlib-forge-1.0.0.jar",
          "url": "magicsrebirthlib-forge-1.0.0.jar",
          "size": 95646,
          "sha512": "0e446a01396852e71dd05aff38da9ce5dd6f7953edb83c72e22ebecec2fb293c6bb6c3ab4167c5a48a55884f42ecd5eed735deddb45175410241250054faaee4",
          "sha256": "8df5c0f3fd558a6d6d9abf682f2a66da9c23786cee6b72097f3c4287bdb49e70",
          "sha1": "dce895fd7e609991d078e9ee060b9ee9a174872f",
          "md5": "a697a560854c743ad132f307f2beff89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.arcnor",
          "module": "universal-tween-engine",
          "version": {
            "requires": "6.3.4"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx",
          "version": {
            "requires": "1.13.5"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.3.0_mapped_official_1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "magicsrebirthlib-forge-1.0.0.jar",
          "url": "magicsrebirthlib-forge-1.0.0.jar",
          "size": 95646,
          "sha512": "0e446a01396852e71dd05aff38da9ce5dd6f7953edb83c72e22ebecec2fb293c6bb6c3ab4167c5a48a55884f42ecd5eed735deddb45175410241250054faaee4",
          "sha256": "8df5c0f3fd558a6d6d9abf682f2a66da9c23786cee6b72097f3c4287bdb49e70",
          "sha1": "dce895fd7e609991d078e9ee060b9ee9a174872f",
          "md5": "a697a560854c743ad132f307f2beff89"
        }
      ]
    }
  ]
}
