{
  "formatVersion": "1.1",
  "component": {
    "group": "th.in.tamkungz",
    "module": "letyourfriendeating-neoforge-1.21.9",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "20.0.148"
          }
        }
      ],
      "files": [
        {
          "name": "letyourfriendeating-neoforge-1.21.9-1.1.0.jar",
          "url": "letyourfriendeating-neoforge-1.21.9-1.1.0.jar",
          "size": 119932,
          "sha512": "277e2cbb8495ca191aad96d149473795746cfb2be8245163e233792f2097d00ed8c36861efeea05d2d4b624df091b2bf8cc0e812fe4ca7621a50a9d122c35eb7",
          "sha256": "30aa25e2d7d94ee1dee4638045827044b50c7dd7fa582be9b99648c72813bafb",
          "sha1": "1e348f01323a1de0c4671fe06d45e9e970498aee",
          "md5": "98b6cdd8107ab48c92796f7286d11512"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoforge",
          "version": {
            "requires": "21.10.38-beta"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "20.0.148"
          }
        }
      ],
      "files": [
        {
          "name": "letyourfriendeating-neoforge-1.21.9-1.1.0.jar",
          "url": "letyourfriendeating-neoforge-1.21.9-1.1.0.jar",
          "size": 119932,
          "sha512": "277e2cbb8495ca191aad96d149473795746cfb2be8245163e233792f2097d00ed8c36861efeea05d2d4b624df091b2bf8cc0e812fe4ca7621a50a9d122c35eb7",
          "sha256": "30aa25e2d7d94ee1dee4638045827044b50c7dd7fa582be9b99648c72813bafb",
          "sha1": "1e348f01323a1de0c4671fe06d45e9e970498aee",
          "md5": "98b6cdd8107ab48c92796f7286d11512"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "letyourfriendeating-neoforge-1.21.9-1.1.0-sources.jar",
          "url": "letyourfriendeating-neoforge-1.21.9-1.1.0-sources.jar",
          "size": 111561,
          "sha512": "14495f2f23eefda23d47a26c96cb7f21970d904eecc8fd6d1d852018dc63802ea8365ad987124f864a96d185f4c774dfe9d80ce9a8b5177f773ec31155eb1389",
          "sha256": "7107878b1b1321e9a703544494b89dc75476a3b0635573fa8806460e8bc80cbe",
          "sha1": "721420ce317f834eea9938334f692c1ba5a7ed0d",
          "md5": "76cd2827c9da636969d25e610fd0979e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "letyourfriendeating-neoforge-1.21.9-1.1.0-javadoc.jar",
          "url": "letyourfriendeating-neoforge-1.21.9-1.1.0-javadoc.jar",
          "size": 133557,
          "sha512": "ab464542638009cbdaa77c8671c41674bbb5b71ebc6a6c7412d37d28575df490b191a9c280d5b18e387a911405d98a64449eb36069530988b8940bf82fac0734",
          "sha256": "3f386b82a516ebc3451c9d7b558271f4e294c656709ec5cf2163e22960dc2211",
          "sha1": "585b45d8c4585b33d4098ed0c2eed9814abe05c0",
          "md5": "867581b83eeb5e364de306624d51c094"
        }
      ]
    }
  ]
}
